export { default as GlitchKitBadRequestHttpError } from './GlitchKitBadRequestHttpError'; // 400
export { default as GlitchKitConflictHttpError } from './GlitchKitConflictHttpError'; // 409
export { default as GlitchKitExpectationFailedHttpError } from './GlitchKitExpectationFailedHttpError'; // 417
export { default as GlitchKitFailedDependencyHttpError } from './GlitchKitFailedDependencyHttpError'; // 424
export { default as GlitchKitForbiddenHttpError } from './GlitchKitForbiddenHttpError'; // 403
export { default as GlitchKitGoneHttpError } from './GlitchKitGoneHttpError'; // 410
export { default as GlitchKitImATeapotHttpError } from './GlitchKitImATeapotHttpError'; // 418
export { default as GlitchKitLengthRequiredHttpError } from './GlitchKitLengthRequiredHttpError'; // 411
export { default as GlitchKitLockedHttpError } from './GlitchKitLockedHttpError'; // 423
export { default as GlitchKitMethodNotAllowedHttpError } from './GlitchKitMethodNotAllowedHttpError'; // 405
export { default as GlitchKitMisdirectedRequestHttpError } from './GlitchKitMisdirectedRequestHttpError'; // 421
export { default as GlitchKitNotAcceptableHttpError } from './GlitchKitNotAcceptableHttpError'; // 406
export { default as GlitchKitNotFoundHttpError } from './GlitchKitNotFoundHttpError'; // 404
export { default as GlitchKitPayloadTooLargeHttpError } from './GlitchKitPayloadTooLargeHttpError'; // 413
export { default as GlitchKitPaymentRequiredHttpError } from './GlitchKitPaymentRequiredHttpError'; // 402
export { default as GlitchKitPreconditionFailedHttpError } from './GlitchKitPreconditionFailedHttpError'; // 412
export { default as GlitchKitPreconditionRequiredHttpError } from './GlitchKitPreconditionRequiredHttpError'; // 428
export { default as GlitchKitProxyAuthenticationRequiredHttpError } from './GlitchKitProxyAuthenticationRequiredHttpError'; // 407
export { default as GlitchKitRangeNotSatisfiableHttpError } from './GlitchKitRangeNotSatisfiableHttpError'; // 416
export { default as GlitchKitRequestHeaderFieldsTooLargeHttpError } from './GlitchKitRequestHeaderFieldsTooLargeHttpError'; // 431
export { default as GlitchKitRequestTimeoutHttpError } from './GlitchKitRequestTimeoutHttpError'; // 408
export { default as GlitchKitTooEarlyHttpError } from './GlitchKitTooEarlyHttpError'; // 425
export { default as GlitchKitTooManyRequestsHttpError } from './GlitchKitTooManyRequestsHttpError'; // 429
export { default as GlitchKitUnauthorizedHttpError } from './GlitchKitUnauthorizedHttpError'; // 401
export { default as GlitchKitUnavailableForLegalReasonsHttpError } from './GlitchKitUnavailableForLegalReasonsHttpError'; // 451
export { default as GlitchKitUnprocessableEntityHttpError } from './GlitchKitUnprocessableEntityHttpError'; // 422
export { default as GlitchKitUnsupportedMediaTypeHttpError } from './GlitchKitUnsupportedMediaTypeHttpError'; // 415
export { default as GlitchKitUpgradeRequiredHttpError } from './GlitchKitUpgradeRequiredHttpError'; // 426
export { default as GlitchKitUriTooLongHttpError } from './GlitchKitUriTooLongHttpError'; // 414

// 5xx Server Errors
export { default as GlitchKitBadGatewayHttpError } from './GlitchKitBadGatewayHttpError'; // 502
export { default as GlitchKitGatewayTimeoutHttpError } from './GlitchKitGatewayTimeoutHttpError'; // 504
export { default as GlitchKitHttpVersionNotSupportedHttpError } from './GlitchKitHttpVersionNotSupportedHttpError'; // 505
export { default as GlitchKitInsufficientStorageHttpError } from './GlitchKitInsufficientStorageHttpError'; // 507
export { default as GlitchKitInternalServerErrorHttpError } from './GlitchKitInternalServerErrorHttpError'; // 500
export { default as GlitchKitLoopDetectedHttpError } from './GlitchKitLoopDetectedHttpError'; // 508
export { default as GlitchKitNetworkAuthenticationRequiredHttpError } from './GlitchKitNetworkAuthenticationRequiredHttpError'; // 511
export { default as GlitchKitNotExtendedHttpError } from './GlitchKitNotExtendedHttpError'; // 510
export { default as GlitchKitNotImplementedHttpError } from './GlitchKitNotImplementedHttpError'; // 501
export { default as GlitchKitServiceUnavailableHttpError } from './GlitchKitServiceUnavailableHttpError'; // 503
export { default as GlitchKitVariantAlsoNegotiatesHttpError } from './GlitchKitVariantAlsoNegotiatesHttpError'; // 506
